port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 7881
    port_range_start: 40000
    port_range_end: 40100
    use_external_ip: true
keys:
    devkey: secret
logging:
    json: false
    level: info
